inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/cache_schema.rb"
    - "db/queue_schema.rb"
    - "db/cable_schema.rb"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"

# Allow longer blocks in specs
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/environments/*"
    - "config/routes.rb"

# Allow longer methods in migrations
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*"

# Allow longer classes
Metrics/ClassLength:
  Max: 200

# Pundit's `permissions` DSL produces examples with identical bodies that test
# different permissions via metadata — false positive for this cop.
RSpec/RepeatedExample:
  Exclude:
    - "spec/policies/**/*"

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4
